/**
 * Exporters turn restored posts into import-ready files for a target platform.
 * Every exporter writes files only — nothing connects to a database, so no
 * credentials are ever needed here. Generated import scripts read keys from
 * environment variables.
 *
 * Add a platform: push an object to EXPORTERS with { id, label, hint, write }.
 */
import fs from "node:fs/promises";
import path from "node:path";
import { toMarkdown, writeMarkdown } from "./output.js";

/** One flat record per post — the shape every database exporter uses */
export function toRecord(post) {
  return {
    slug: post.slug,
    path: post.path,
    title: post.title ?? "",
    excerpt: post.description ?? null,
    content: post.html ?? "",
    featured_image: post.featuredImage ?? null,
    published_at: post.publishedAt ?? null,
    updated_at: post.modifiedAt ?? null,
    author: post.author ?? null,
    categories: post.categories ?? [],
    tags: post.tags ?? [],
    lang: post.lang ?? null,
    type: post.type,
    original_url: post.url,
    archived_at: post.archivedAt,
  };
}

const COLUMNS = Object.keys(toRecord({}));
const ARRAY_COLUMNS = new Set(["categories", "tags"]);
const DATE_COLUMNS = new Set(["published_at", "updated_at"]);

const write = async (outDir, relative, contents) => {
  const file = path.join(outDir, relative);
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, contents);
  return relative;
};

/** Safe SQL identifier: letters, numbers and underscores only */
export const sqlIdentifier = (name = "posts") => {
  const clean = String(name).replace(/[^A-Za-z0-9_]/g, "_").replace(/^(\d)/, "_$1");
  return clean || "posts";
};

// ---------------------------------------------------------------- SQL

const SQL_DIALECTS = {
  postgres: {
    quote: (id) => `"${id}"`,
    string: (s) => `'${s.replace(/'/g, "''")}'`,
    types: { text: "TEXT", date: "TIMESTAMPTZ", json: "JSONB", key: "TEXT" },
    upsert: (table, cols) =>
      `ON CONFLICT ("slug") DO UPDATE SET ${cols.filter((c) => c !== "slug").map((c) => `"${c}" = EXCLUDED."${c}"`).join(", ")}`,
  },
  mysql: {
    quote: (id) => `\`${id}\``,
    // MySQL treats backslash as an escape character inside strings
    string: (s) => `'${s.replace(/\\/g, "\\\\").replace(/'/g, "''")}'`,
    types: { text: "LONGTEXT", date: "DATETIME", json: "JSON", key: "VARCHAR(512)" },
    upsert: (table, cols) =>
      `ON DUPLICATE KEY UPDATE ${cols.filter((c) => c !== "slug").map((c) => `\`${c}\` = VALUES(\`${c}\`)`).join(", ")}`,
  },
  sqlite: {
    quote: (id) => `"${id}"`,
    string: (s) => `'${s.replace(/'/g, "''")}'`,
    types: { text: "TEXT", date: "TEXT", json: "TEXT", key: "TEXT" },
    upsert: (table, cols) =>
      `ON CONFLICT ("slug") DO UPDATE SET ${cols.filter((c) => c !== "slug").map((c) => `"${c}" = excluded."${c}"`).join(", ")}`,
  },
};

/** MySQL DATETIME has no timezone: store as UTC "YYYY-MM-DD HH:MM:SS" */
const mysqlDate = (value) => {
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? null : date.toISOString().slice(0, 19).replace("T", " ");
};

export function toSql(posts, { dialect = "postgres", table = "posts" } = {}) {
  const d = SQL_DIALECTS[dialect];
  if (!d) throw new Error(`Unknown SQL dialect "${dialect}" (postgres, mysql, sqlite)`);
  const t = d.quote(sqlIdentifier(table));
  const type = (c) =>
    c === "slug" ? `${d.types.key} PRIMARY KEY`
    : ARRAY_COLUMNS.has(c) ? d.types.json
    : DATE_COLUMNS.has(c) ? d.types.date
    : d.types.text;

  const value = (column, v) => {
    if (v === null || v === undefined) return "NULL";
    if (ARRAY_COLUMNS.has(column)) return d.string(JSON.stringify(v));
    if (DATE_COLUMNS.has(column) && dialect === "mysql") {
      const date = mysqlDate(v);
      return date ? d.string(date) : "NULL";
    }
    return d.string(String(v));
  };

  const lines = [
    `-- Generated by wayback-restore (${posts.length} posts, ${dialect})`,
    dialect === "mysql" ? "SET NAMES utf8mb4;" : null,
    `CREATE TABLE IF NOT EXISTS ${t} (\n${COLUMNS.map((c) => `  ${d.quote(c)} ${type(c)}`).join(",\n")}\n)${dialect === "mysql" ? " DEFAULT CHARSET=utf8mb4" : ""};`,
    "",
  ].filter((line) => line !== null);

  for (const post of posts) {
    const record = toRecord(post);
    lines.push(
      `INSERT INTO ${t} (${COLUMNS.map(d.quote).join(", ")})\nVALUES (${COLUMNS.map((c) => value(c, record[c])).join(", ")})\n${d.upsert(t, COLUMNS)};`,
    );
  }
  return `${lines.join("\n")}\n`;
}

// ---------------------------------------------------------------- CSV

export function toCsv(posts) {
  const cell = (v) => {
    const text = v === null || v === undefined ? "" : Array.isArray(v) ? v.join("|") : String(v);
    return /[",\r\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
  };
  const rows = posts.map((p) => {
    const r = toRecord(p);
    return COLUMNS.map((c) => cell(r[c])).join(",");
  });
  // BOM so Excel opens Arabic text correctly
  return `﻿${COLUMNS.join(",")}\r\n${rows.join("\r\n")}\r\n`;
}

// ---------------------------------------------------------------- MongoDB

/** NDJSON in MongoDB Extended JSON (dates as $date) — ready for `mongoimport` */
export function toMongoNdjson(posts) {
  return posts
    .map((p) => {
      const r = toRecord(p);
      for (const c of DATE_COLUMNS) if (r[c]) r[c] = { $date: new Date(r[c]).toISOString() };
      return JSON.stringify({ _id: r.slug, ...r });
    })
    .join("\n")
    .concat("\n");
}

// ---------------------------------------------------------------- WordPress (WXR)

const cdata = (s = "") => `<![CDATA[${String(s).replace(/]]>/g, "]]]]><![CDATA[>")}]]>`;
const xml = (s = "") => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
const wpDate = (value) => {
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? "" : date.toISOString().slice(0, 19).replace("T", " ");
};
const termSlug = (name) => encodeURIComponent(name.trim().toLowerCase().replace(/\s+/g, "-"));

/** WordPress eXtended RSS — import with Tools → Import → WordPress */
export function toWxr(posts, { siteUrl = "", siteName = "Restored site" } = {}) {
  const items = posts.map((post, i) => {
    const date = post.publishedAt || post.archivedAt?.replace(/^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2}).*/, "$1-$2-$3T$4:$5:$6Z");
    const terms = [
      ...(post.categories || []).map((c) => `<category domain="category" nicename="${termSlug(c)}">${cdata(c)}</category>`),
      ...(post.tags || []).map((t) => `<category domain="post_tag" nicename="${termSlug(t)}">${cdata(t)}</category>`),
    ];
    return `  <item>
    <title>${cdata(post.title)}</title>
    <link>${xml(post.url)}</link>
    <dc:creator>${cdata(post.author || "admin")}</dc:creator>
    <description></description>
    <content:encoded>${cdata(post.html)}</content:encoded>
    <excerpt:encoded>${cdata(post.description || "")}</excerpt:encoded>
    <wp:post_id>${i + 1}</wp:post_id>
    <wp:post_date>${cdata(wpDate(date))}</wp:post_date>
    <wp:post_date_gmt>${cdata(wpDate(date))}</wp:post_date_gmt>
    <wp:post_name>${cdata(encodeURIComponent(post.slug.split("/").pop()))}</wp:post_name>
    <wp:status>${cdata("publish")}</wp:status>
    <wp:post_type>${cdata(post.type === "page" ? "page" : "post")}</wp:post_type>
    ${terms.join("\n    ")}
  </item>`;
  });
  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by wayback-restore — import with WordPress: Tools → Import → WordPress -->
<rss version="2.0"
  xmlns:excerpt="http://wordpress.org/export/1.2/excerpt/"
  xmlns:content="http://purl.org/rss/1.0/modules/content/"
  xmlns:wfw="http://wellformedweb.org/CommentAPI/"
  xmlns:dc="http://purl.org/dc/elements/1.1/"
  xmlns:wp="http://wordpress.org/export/1.2/">
<channel>
  <title>${xml(siteName)}</title>
  <link>${xml(siteUrl)}</link>
  <wp:wxr_version>1.2</wp:wxr_version>
  <wp:base_site_url>${xml(siteUrl)}</wp:base_site_url>
  <wp:base_blog_url>${xml(siteUrl)}</wp:base_blog_url>
${items.join("\n")}
</channel>
</rss>
`;
}

// ---------------------------------------------------------------- Prisma & Supabase

export const prismaModel = (table = "posts") => {
  const name = sqlIdentifier(table);
  const model = name.charAt(0).toUpperCase() + name.slice(1).replace(/_(\w)/g, (_, c) => c.toUpperCase()).replace(/s$/, "");
  return `// Add this model to prisma/schema.prisma, then run: npx prisma migrate dev
model ${model} {
  slug          String    @id
  path          String
  title         String
  excerpt       String?
  content       String
  featuredImage String?   @map("featured_image")
  publishedAt   DateTime? @map("published_at")
  updatedAt     DateTime? @map("updated_at")
  author        String?
  categories    String[]
  tags          String[]
  lang          String?
  type          String
  originalUrl   String    @map("original_url")
  archivedAt    String    @map("archived_at")

  @@map("${name}")
}
`;
};

const prismaSeed = (table) => {
  const name = sqlIdentifier(table);
  const accessor = prismaModel(table).match(/^model (\w+)/m)[1].replace(/^./, (c) => c.toLowerCase());
  return `// Generated by wayback-restore — imports posts.json with Prisma.
// Usage: node prisma/import-${name}.mjs   (DATABASE_URL must be set, schema migrated)
// Note: String[] needs PostgreSQL or CockroachDB. For MySQL/SQLite store them as Json instead.
import { readFile } from "node:fs/promises";
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();
const posts = JSON.parse(await readFile(new URL("../posts.json", import.meta.url), "utf8"));
const date = (v) => (v ? new Date(v) : null);

for (const p of posts) {
  const data = {
    path: p.path,
    title: p.title ?? "",
    excerpt: p.description ?? null,
    content: p.html ?? "",
    featuredImage: p.featuredImage ?? null,
    publishedAt: date(p.publishedAt),
    updatedAt: date(p.modifiedAt),
    author: p.author ?? null,
    categories: p.categories ?? [],
    tags: p.tags ?? [],
    lang: p.lang ?? null,
    type: p.type,
    originalUrl: p.url,
    archivedAt: p.archivedAt,
  };
  await prisma.${accessor}.upsert({ where: { slug: p.slug }, create: { slug: p.slug, ...data }, update: data });
}
console.log(\`Imported \${posts.length} posts\`);
await prisma.$disconnect();
`;
};

const supabaseMigration = (table) => {
  const name = sqlIdentifier(table);
  return `-- Generated by wayback-restore — run in Supabase: SQL Editor → New query
create table if not exists public.${name} (
  slug           text primary key,
  path           text not null,
  title          text not null,
  excerpt        text,
  content        text not null,
  featured_image text,
  published_at   timestamptz,
  updated_at     timestamptz,
  author         text,
  categories     jsonb not null default '[]',
  tags           jsonb not null default '[]',
  lang           text,
  type           text,
  original_url   text,
  archived_at    text
);

-- Anyone can read published posts; only the service role (server-side) can write
alter table public.${name} enable row level security;
create policy "${name} are publicly readable" on public.${name} for select using (true);
`;
};

const supabaseImport = (table) => `// Generated by wayback-restore — upserts posts.json into Supabase.
// Usage (keys come from the environment — never hard-code them):
//   SUPABASE_URL=... SUPABASE_SERVICE_ROLE_KEY=... node supabase/import-${sqlIdentifier(table)}.mjs
// Run supabase/migration.sql first. Needs: npm i @supabase/supabase-js
import { readFile } from "node:fs/promises";
import { createClient } from "@supabase/supabase-js";

const { SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY } = process.env;
if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
  console.error("Set SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY first.");
  process.exit(1);
}
const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, { auth: { persistSession: false } });
const records = JSON.parse(await readFile(new URL("./${sqlIdentifier(table)}.json", import.meta.url), "utf8"));

for (let i = 0; i < records.length; i += 100) {
  const { error } = await supabase.from("${sqlIdentifier(table)}").upsert(records.slice(i, i + 100), { onConflict: "slug" });
  if (error) throw error;
  console.log(\`Imported \${Math.min(i + 100, records.length)}/\${records.length}\`);
}
`;

// ---------------------------------------------------------------- registry

export const EXPORTERS = [
  {
    id: "json",
    label: "JSON",
    hint: "posts.json · works with anything",
    write: async (posts, { outDir }) => [await write(outDir, "posts.json", JSON.stringify(posts, null, 2))],
  },
  {
    id: "md",
    label: "Markdown",
    hint: "Next.js, Astro, Hugo, Jekyll · frontmatter + body",
    write: async (posts, { outDir }) => {
      const files = [];
      for (const post of posts) files.push(path.relative(outDir, await writeMarkdown(post, outDir)));
      return files;
    },
  },
  {
    id: "supabase",
    label: "Supabase",
    hint: "migration.sql + upsert script · keys from env",
    write: async (posts, { outDir, table }) => [
      await write(outDir, "supabase/migration.sql", supabaseMigration(table)),
      await write(outDir, `supabase/${sqlIdentifier(table)}.json`, JSON.stringify(posts.map(toRecord), null, 2)),
      await write(outDir, `supabase/import-${sqlIdentifier(table)}.mjs`, supabaseImport(table)),
    ],
  },
  {
    id: "prisma",
    label: "Prisma",
    hint: "schema model + import script",
    write: async (posts, { outDir, table }) => [
      await write(outDir, "prisma/model.prisma", prismaModel(table)),
      await write(outDir, `prisma/import-${sqlIdentifier(table)}.mjs`, prismaSeed(table)),
    ],
  },
  {
    id: "postgres",
    label: "PostgreSQL",
    hint: "posts.postgres.sql · CREATE + upsert",
    write: async (posts, { outDir, table }) => [await write(outDir, "sql/posts.postgres.sql", toSql(posts, { dialect: "postgres", table }))],
  },
  {
    id: "mysql",
    label: "MySQL / MariaDB",
    hint: "posts.mysql.sql · utf8mb4",
    write: async (posts, { outDir, table }) => [await write(outDir, "sql/posts.mysql.sql", toSql(posts, { dialect: "mysql", table }))],
  },
  {
    id: "sqlite",
    label: "SQLite",
    hint: "posts.sqlite.sql",
    write: async (posts, { outDir, table }) => [await write(outDir, "sql/posts.sqlite.sql", toSql(posts, { dialect: "sqlite", table }))],
  },
  {
    id: "mongodb",
    label: "MongoDB",
    hint: "posts.ndjson for mongoimport",
    write: async (posts, { outDir }) => [await write(outDir, "mongodb/posts.ndjson", toMongoNdjson(posts))],
  },
  {
    id: "csv",
    label: "CSV",
    hint: "Excel, Google Sheets, Airtable, Notion",
    write: async (posts, { outDir }) => [await write(outDir, "posts.csv", toCsv(posts))],
  },
  {
    id: "wordpress",
    label: "WordPress (WXR)",
    hint: "re-import into a fresh WordPress: Tools → Import",
    write: async (posts, { outDir, domain }) => [
      await write(outDir, "wordpress/wordpress-export.xml", toWxr(posts, { siteUrl: `https://${domain}`, siteName: domain })),
    ],
  },
];

export const EXPORTER_IDS = EXPORTERS.map((e) => e.id);

/** Run the chosen exporters; returns the list of written files (relative to outDir) */
export async function exportPosts(posts, { formats = ["json"], outDir, table = "posts", domain = "" }) {
  const unknown = formats.filter((f) => !EXPORTER_IDS.includes(f));
  if (unknown.length) throw new Error(`Unknown format(s): ${unknown.join(", ")}. Available: ${EXPORTER_IDS.join(", ")}`);
  const files = [];
  for (const exporter of EXPORTERS.filter((e) => formats.includes(e.id))) {
    files.push(...(await exporter.write(posts, { outDir, table, domain })));
  }
  return files;
}

export { toMarkdown };
